# Page settings

baseURL = "https://gabriele.lucci.xyz/"
languageCode = "en"
title = "Gabriele Lucci's resume"
theme = "hugo-devresume-theme"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
author = "Gabriele Lucci"
description = "Gabriele Lucci's resume - english"

[params.profile]
enable = true
name = "Gabriele Lucci"
tagline = "Software developer"
avatar = false

[params.contact]
enable = true

# [[params.contact.list]]
# icon = "fas fa-map-marked-alt"
# url = "geo://41.83909,12.89068"
# text = "Palestrina, RM"
[[params.contact.list]]
icon = "fas fa-envelope"
url = "mailto://gabriele@lucci.xyz"
text = "gabriele@lucci.xyz"
[[params.contact.list]]
icon = "fab fa-github"
url = "https://github.com/gabrielelucci"
text = "GitHub"
[[params.contact.list]]
icon = "fab fa-gitlab"
url = "https://gitlab.com/gabrielelucci"
text = "GitLab.com"
[[params.contact.list]]
icon = "fas fa-comments"
url = "https://matrix.to/#/@gabrielelucci_xyz:matrix.org"
text = "Matrix"
[[params.contact.list]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/gabriele-lucci-7a905b118"
text = "LinkedIn"

[params.skills]
enable = true

[[params.skills.list]]
title = "Programming"
[[params.skills.list.items]]
details = "Python"
[[params.skills.list.items]]
details = "Golang"
[[params.skills.list.items]]
details = "Javascript / Node.js"
[[params.skills.list.items]]
details = "Java / Android"

[[params.skills.list]]
title = "Web development"
[[params.skills.list.items]]
details = "Django / Flask"
[[params.skills.list.items]]
details = "SQL (Postgres, SQLite)"
[[params.skills.list.items]]
details = "Data modeling"
[[params.skills.list.items]]
details = "HTTP API design"
[[params.skills.list.items]]
details = "Containerization"
[[params.skills.list.items]]
details = "Full Text-search"
[[params.skills.list.items]]
details = "Scraping / ETL"

[[params.skills.list]]
title = "Tooling"
[[params.skills.list.items]]
details = "Version control (Git)"
[[params.skills.list.items]]
details = "Repository management (GitLab, GitHub, Bitbucket)"
[[params.skills.list.items]]
details = "OCI Containers (Docker, Podman)"
[[params.skills.list.items]]
details = "Python (mypy, ruff, uv)"
[[params.skills.list.items]]
details = "IDE (PyCharm, VSCode)"

[[params.skills.list]]
title = "SysAdmin"
[[params.skills.list.items]]
details = "Linux (Debian, RedHat, Arch)"
[[params.skills.list.items]]
details = "Web servers (Nginx, Caddy, Apache)"
[[params.skills.list.items]]
details = "Container orchestration (Compose, Kubernetes)"
[[params.skills.list.items]]
details = "Monitoring (Prometheus, Grafana)"

[params.education]
enable = true

[[params.education.list]]
degree = "Higher Technical Institute diploma"
iscedCode = "3"
university = "IISS J. Von Neumann"
city = "Rome"
dates = "2009 - 2016"

# [[params.education.list]]
# degree = "BSc Maths and Physics"
# university = "Imperial College London"
# dates = "2007 - 2010"

# [params.awards]
# enable = true
#
# [[params.awards.list]]
# name = "Award Lorem Ipsum"
# body = "Microsoft lorem ipsum"
# date = "2019"
# [[params.awards.list]]
# name = "Award Donec Sodales"
# body = "Oracle Aenean"
# date = "2017"

[params.languages]
enable = true

[[params.languages.list]]
name = "Italiano"
level = "Native"
[[params.languages.list]]
name = "English"
level = "C1 - Proficient"
[[params.languages.list]]
name = "汉语"
level = "A1 - Beginner"

[params.interests]
enable = true
[[params.interests.list]]
name = "Music"
[[params.interests.list]]
name = "Coffee"
[[params.interests.list]]
name = "Cooking"
[[params.interests.list]]
name = "Videogames"
[[params.interests.list]]
name = "Inline skating"

[params.summary]
enable = true
text = """
I'm a software developer with professional experience in __Python__ and __JavaScript/Node.js__, particularly on the backend side of web development, with a proven track record on delivering cloud-native solutions from the drawing board to production.

I'm a detail-oriented perfectionist, but also versatile and constantly looking for new challenges. I enjoy working with __Django__ (who doesn't? ), but I'm always open to learning new technologies. Additionally, I'm quite proficient in administering __Linux__ systems, which I've been using in some form or another since I was a kid.

In my spare time, I especially enjoy engaging in various music-related activities, such as playing bass guitar with [my friends](https://www.instagram.com/lefogliemusic/).
"""

[params.experience]
enable = true

[[params.experience.list]]
title = "Technician / Full stack developer"
dates = "May 2021 - Dec 2023"
company = "Eurac Research (Institute of Biomedicine)"
details = """
As part of the IT team at the [Institute for Biomedicine](https://www.eurac.edu/en/institutes-center/institute-for-biomedicine) of Eurac Research, I worked primarily on the [CHRIS-2D](https://www.eurac.edu/en/institutes-center/institute-for-biomedicine/projects/chris-2d) project, which involved the creation of a “dynamic data portal”, a web app enabling researchers, even from outside institutions, to peruse a set of the data gathered by Eurac's IfB studies.

Due to the small size of our development team, we decided to build the portal as a full-stack __Django__ application, that included an HTTP API to be queried by complementary internal tools. I played a significant role in deciding the project's architecture and implementation;  it's been a real benchmark of my skills that was ultimately a success, and I'm quite proud of what was achieved.
"""

[[params.experience.list]]
title = "Backend developer"
dates = "Jul 2017 - Jan 2021"
company = "Fondazione Openpolis"
details = """
I worked for the [Openpolis Foundation](https://www.openpolis.it/), supporting their editorial team by developing multiple web applications and toolkits using __Python__ and __Django__.

Those are the most relevant projects I was involed in:
- "[Mappe del potere](https://fondazione.openpolis.it/en/cosa-facciamo/mappe-del-potere)": essentially a database of all things related to Italian politicians, modeled following the [Popolo](https://www.popoloproject.com/) open specification. It essentially consists of a core implemented as an open-source [Django app](https://github.com/openpolis/django-popolo), a complex *REST API* that exposes the underlying data, and a [custom-built task manager](https://github.com/openpolis/django-uwsgi-taskmanager) to handle and scheduling background tasks. The data was gathered from numerous different sources (HTTP APIs, *SPARQL*, *web scraping*) by ETL pipelines.
- "[Povertà educativa](https://www.openpolis.it/poverta-educativa/)": a project that shares a lot of components and concepts with the previously listed one, but with a particular focus on the socio-economic conditions of minors in Italy.
- "[A schede scoperte](https://www.openpolis.it/schede-scoperte-politiche-2018/)": an application implemented in Django and **React**, with the purpose of promoting transparency during the 2018 Italian general elections.

This was a pivotal role for my career, as I was lucky enough to have an expert mentor who taught me a lot of extremely valuable skills that I consider fundamental to my profile.
"""

[[params.experience.list]]
title = "Full stack developer"
dates = "Sep 2016 - Jul 2017"
company = "Anansi Team"
details = """
I was the lead developer of "APA Cloud", a suite of server side applications that would gather, store, and visualize air quality sensor data. Mainly developed using __Node.js__ ([LoopBack 3](https://loopback.io/) and [Sails.js](https://sailsjs.com/)) for the backend, and __Angular v1__ for the frontend.

"""

[params.projects]
enable = true

[[params.projects.list]]
title = "My own self-hosted \"cloud\""
meta = "a.k.a. \"LucciCloud\""
tagline = """
I've been maintaining an array of self-hosted services for years.

Some of the services I run (there are more, but these are the most relevant):
 - a bunch of [Fediverse](https://en.wikipedia.org/wiki/Fediverse) nodes ([**Mastodon**](https://joinmastodon.org/), [GoToSocial](https://gotosocial.org/))
 - a [**Nextcloud**](https://nextcloud.com) server, which I use daily to back up my photos, store documents and sync contacts and calendars between my personal devices.
 - [Grocy](https://grocy.info/), an ERP for managing groceries and alike.
 - a Minecraft game server because… why not?
  - [this very website](https://gitlab.com/gabrielelucci/hugo-resume) (made with [**Hugo**](https://gohugo.io/))!

Everything is deployed and orchestrated [using containers](https://gitlab.com/gabrielelucci/cloud) on rented Linux hosts. Services that expose HTTP functionalities are proxied using **Caddy**, which automatically handles certificates and also acts as load balancer. Additionally, pretty much everything is "instrumented" using [**Prometheus**](https://prometheus.io/) and monitored using [**Grafana**](https://grafana.com/).

I'm very proud of this project, it taught me plenty of skills that complement my developer profile quite well, and I consider it a great way to keep up with the latest trends in the field.
"""

[[params.projects.list]]
title = "Private \"AI lab\""
meta = "Experimenting with local LLMs"
tagline = """
I've been experimenting with local LLMs for a while now, using llama.cpp and various complementary tools to run models locally on my own hardware. I have a few different models running, that I employ for different tasks, such as **Llama** for conversational tasks, **Deepseek Coder** for Copilot-like code generation and completion, Granite for text embedding of documents, and others.

To make the usage of these models easier, I employed simple frontend solutions such as [**Open WebUI**](https://openwebui.com/) and [**ComfyUI**](https://www.comfy.org/), which allow me to query the models using a web interface.

This is a fun project that helps me to keep up with the latest developments in the field of AI. It also provided me with a basic understanding of what it takes to deploy local models, a skill that could be useful in contexts where data privacy is a concern and the use of cloud services isn't desirable.
"""
# [params.information]
# enable = true
#
# [[params.information.list]]
# title = "Papers"
# [[params.information.list.items]]
# details = "2018 · Lorem Ipsum"
# [[params.information.list.items]]
# details = "2016 · Sed Fringilla"
# [[params.information.list]]
# title = "Interests"
# details = "Climbing, Snowboarding, Photography, Travelling"

[params.social]
enable = false

[[params.social.list]]
icon = "fab fa-mastodon"
url = "https://mastodon.lucci.xyz/@gabriele"
title = "@gabriele"
# [[params.social.list]]
# icon = "fab fa-spotify"
# url = "https://open.spotify.com/user/gabrielelucci"
# title = "gabrielelucci"

[params.footer]
enable = true
copyright = "Gabriele Lucci"

