# Page settings

baseURL = "https://gabriele.lucci.xyz/resume/"
languageCode = "en"
title = "Gabriele Lucci's resume"
theme = "hugo-devresume-theme"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
author = "Gabriele Lucci"
description = "Software developer experienced in Python, Django, JavaScript and Node.js, specializing in backend web development and cloud-native solutions."
keywords = ["software developer", "web developer", "python", "django", "nodejs", "javascript", "golang", "flask"]
canonical = "https://gabriele.lucci.xyz/resume"

[params.profile]
enable = true
name = "Gabriele Lucci"
tagline = "Software developer"
avatar = false

[params.contact]
enable = true

[[params.contact.list]]
icon = "fas fa-map-marked-alt"
url = "geo:41.83909,12.89068"
text = "Palestrina, RM, Italy"
[[params.contact.list]]
icon = "fas fa-envelope"
url = "mailto:gabriele@lucci.xyz"
text = "gabriele@lucci.xyz"
[[params.contact.list]]
icon = "fab fa-github"
url = "https://github.com/gabrielelucci"
text = "GitHub"
[[params.contact.list]]
icon = "fab fa-gitlab"
url = "https://gitlab.com/gabrielelucci"
text = "GitLab.com"
[[params.contact.list]]
icon = "fas fa-comments"
url = "https://matrix.to/#/@gabrielelucci_xyz:matrix.org"
text = "Matrix"
[[params.contact.list]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/gabriele-lucci-7a905b118"
text = "LinkedIn"

[params.skills]
enable = true

[[params.skills.list]]
title = "Programming"
[[params.skills.list.items]]
details = "Python"
[[params.skills.list.items]]
details = "Golang"
[[params.skills.list.items]]
details = "Javascript / Node.js"
[[params.skills.list.items]]
details = "Java / Android"

[[params.skills.list]]
title = "Web development"
[[params.skills.list.items]]
details = "Django / Flask"
[[params.skills.list.items]]
details = "SQL (Postgres, SQLite)"
[[params.skills.list.items]]
details = "Data modeling"
[[params.skills.list.items]]
details = "HTTP API design"
[[params.skills.list.items]]
details = "Containerization"
[[params.skills.list.items]]
details = "Full Text-search"
[[params.skills.list.items]]
details = "Scraping / ETL"

[[params.skills.list]]
title = "Tooling"
[[params.skills.list.items]]
details = "Version control (Git)"
[[params.skills.list.items]]
details = "Repository management (GitLab, GitHub, Bitbucket)"
[[params.skills.list.items]]
details = "OCI Containers (Docker, Podman)"
[[params.skills.list.items]]
details = "Python (mypy, ruff, uv)"
[[params.skills.list.items]]
details = "IDE (PyCharm, VSCode)"

[[params.skills.list]]
title = "SysAdmin"
[[params.skills.list.items]]
details = "Linux (Debian, RedHat, Arch)"
[[params.skills.list.items]]
details = "Web servers (Nginx, Caddy, Apache)"
[[params.skills.list.items]]
details = "Container orchestration (Compose, Kubernetes)"
[[params.skills.list.items]]
details = "Monitoring (Prometheus, Grafana)"

[params.education]
enable = true

[[params.education.list]]
degree = "Higher Technical Institute diploma"
iscedCode = "3"
university = "IISS J. Von Neumann"
city = "Rome"
dates = "2009 - 2016"

# [[params.education.list]]
# degree = "BSc Maths and Physics"
# university = "Imperial College London"
# dates = "2007 - 2010"

# [params.awards]
# enable = true
#
# [[params.awards.list]]
# name = "Award Lorem Ipsum"
# body = "Microsoft lorem ipsum"
# date = "2019"
# [[params.awards.list]]
# name = "Award Donec Sodales"
# body = "Oracle Aenean"
# date = "2017"

[params.languages]
enable = true

[[params.languages.list]]
name = "Italiano"
level = "Native"
[[params.languages.list]]
name = "English"
level = "C1 - Proficient"
[[params.languages.list]]
name = "汉语"
level = "A1 - Beginner"

[params.interests]
enable = false
[[params.interests.list]]
name = "Music"
[[params.interests.list]]
name = "Coffee"
[[params.interests.list]]
name = "Cooking"
[[params.interests.list]]
name = "Videogames"
[[params.interests.list]]
name = "Inline skating"

[params.summary]
enable = true
text = """
I'm a software developer with professional experience in __Python__ and __JavaScript/Node.js__, particularly on the backend side of web development, with a proven track record on delivering cloud-native solutions from the drawing board to production.

I'm a detail-oriented perfectionist, but also versatile and constantly looking for new challenges. I enjoy working with __Django__ (who doesn't? ), but I'm always open to learning new technologies. Additionally, I'm quite proficient in administering __Linux__ systems, which I've been using in some form or another since I was a kid.

In my spare time, I especially enjoy engaging in various music-related activities, such as playing bass guitar with [my friends](https://www.instagram.com/lefogliemusic/).
"""

[params.experience]
enable = true

[[params.experience.list]]
title = "Django developer"
dates = "Jun 2025 - Feb 2026"
company = "I Mille"
details = """
* Developed custom-tailored Content Management System (CMS) solutions using __Django CMS__.
* Delivered projects for prominent enterprise clients, including Barilla, Maire Group, Cotral, and Locauto.
"""

[[params.experience.list]]
title = "Salesforce Developer"
dates = "Apr 2024 - Sep 2024"
company = "Alpenite"
details = """
* Developed and maintained e-commerce platforms utilizing Salesforce Commerce Cloud.
* Delivered technical solutions for high-profile retail clients, including Pinko and Golden Goose.
"""

[[params.experience.list]]
title = "Technician / Full stack developer"
dates = "May 2021 - Dec 2023"
company = "Eurac Research (Institute for Biomedicine)"
details = """
* Developed a "dynamic data portal" for the [CHRIS-2D](https://www.eurac.edu/en/institutes-center/institute-for-biomedicine/projects/chris-2d) project at Eurac Research's [Institute for Biomedicine](https://www.eurac.edu/en/institutes-center/institute-for-biomedicine), enabling internal and external researchers to explore gathered study data.
* Built the portal as a full-stack **Django** application, featuring an HTTP API designed to integrate with complementary internal tools.
* Played a key role in designing the project's architecture and driving its successful technical implementation.
"""

[[params.experience.list]]
title = "Backend developer"
dates = "Jul 2017 - Jan 2021"
company = "Fondazione Openpolis"
details = """
- Developed web applications and toolkits with __Django__ and __Python__ to support the [Openpolis Foundation](https://www.openpolis.it/)'s editorial team.
- "[Mappe del potere](https://fondazione.openpolis.it/en/cosa-facciamo/mappe-del-potere)": Built an open-source database of Italian politicians ([Popolo](https://www.popoloproject.com/) spec) featuring a Django core, _REST API_, custom background task manager, and _ETL pipelines_ for data gathering (APIs, SPARQL, web scraping).
- "[Povertà educativa](https://www.openpolis.it/poverta-educativa/)": Adapted the existing architecture to track and analyze the socio-economic conditions of minors in Italy.
- "[A schede scoperte](https://www.openpolis.it/schede-scoperte-politiche-2018/)": Created a Django and React application to promote transparency during the 2018 Italian general elections.
- Experienced a pivotal career phase, gaining fundamental professional skills through expert mentorship.
"""

[[params.experience.list]]
title = "Full stack developer"
dates = "Sep 2016 - Jul 2017"
company = "Anansi Team"
details = """
- Led the development of "APA Cloud," a server-side application suite designed to gather, store, and visualize air quality sensor data.
- Built the backend infrastructure using __Node.js__, specifically leveraging the LoopBack 3 and Sails.js frameworks.
- Developed the frontend data visualization and user interface utilizing __Angular v1__.
"""

[params.projects]
enable = true

[[params.projects.list]]
title = "My own self-hosted \"cloud\""
meta = "a.k.a. \"LucciCloud\""
tagline = """
I've been maintaining an array of self-hosted services for years, including but not limited to:
 - a bunch of [Fediverse](https://en.wikipedia.org/wiki/Fediverse) nodes ([**Mastodon**](https://joinmastodon.org/), [GoToSocial](https://gotosocial.org/))
 - a [**Nextcloud**](https://nextcloud.com) server, which I use daily to back up my photos, store documents and sync contacts and calendars between my personal devices.
 - [Grocy](https://grocy.info/), an ERP for managing groceries and alike.
 - a Minecraft game server because… why not?
  - [this very resume](https://gitlab.com/gabrielelucci/hugo-resume) (made with [**Hugo**](https://gohugo.io/))!

Everything is deployed and orchestrated [using containers](https://gitlab.com/gabrielelucci/cloud) on rented Linux hosts. Services that expose HTTP functionalities are proxied using **Caddy**, which automatically handles certificates and also acts as load balancer. Additionally, pretty much everything is "instrumented" using [**Prometheus**](https://prometheus.io/) and monitored using [**Grafana**](https://grafana.com/).

I'm very proud of this project, it taught me plenty of skills that complement my developer profile quite well, and I consider it a great way to keep up with the latest trends in the field.
"""

[[params.projects.list]]
title = "Private \"AI lab\""
meta = "Experimenting with local LLMs"
tagline = """
I've been experimenting with local LLMs for a while now, using llama.cpp and various complementary tools to run models locally on my own hardware. I have a few different models running, that I employ for different tasks, such as **Llama** for conversational tasks, **Deepseek Coder** for Copilot-like code generation and completion, Granite for text embedding of documents, and others.

To make the usage of these models easier, I employed simple frontend solutions such as [**Open WebUI**](https://openwebui.com/) and [**ComfyUI**](https://www.comfy.org/), which allow me to query the models using a web interface.

This is a fun project that helps me to keep up with the latest developments in the field of AI. It also provided me with a basic understanding of what it takes to deploy local models, a skill that could be useful in contexts where data privacy is a concern and the use of cloud services isn't desirable.
"""
# [params.information]
# enable = true
#
# [[params.information.list]]
# title = "Papers"
# [[params.information.list.items]]
# details = "2018 · Lorem Ipsum"
# [[params.information.list.items]]
# details = "2016 · Sed Fringilla"
# [[params.information.list]]
# title = "Interests"
# details = "Climbing, Snowboarding, Photography, Travelling"

[params.social]
enable = false

[[params.social.list]]
icon = "fab fa-mastodon"
url = "https://mastodon.lucci.xyz/@gabriele"
title = "@gabriele"
# [[params.social.list]]
# icon = "fab fa-spotify"
# url = "https://open.spotify.com/user/gabrielelucci"
# title = "gabrielelucci"

[params.footer]
enable = true
copyright = "Gabriele Lucci"

